-- ============================================================
-- CSU REGISTRAR VERIFICATION SYSTEM — SUPABASE SQL SCHEMA
-- Paste this entire file into Supabase → SQL Editor → Run
-- ============================================================


-- ============================================================
-- SECTION 1: EXTENSIONS
-- ============================================================

-- Enable UUID generation (already enabled in Supabase by default)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
-- SECTION 2: USERS TABLE
-- Stores profile data for both students/clients and admin staff.
-- Linked 1:1 to Supabase Auth (auth.users).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
    id              UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email           TEXT        NOT NULL UNIQUE,
    display_name    TEXT        NOT NULL,
    role            TEXT        NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index: fast lookup by email and role
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role  ON public.users(role);

-- Comment
COMMENT ON TABLE  public.users              IS 'User profiles — students/clients and registrar staff.';
COMMENT ON COLUMN public.users.id           IS 'Matches auth.users.id (Supabase Auth UID).';
COMMENT ON COLUMN public.users.role         IS '"user" = student/client, "admin" = registrar staff.';


-- ============================================================
-- SECTION 3: VERIFICATION REQUESTS TABLE
-- One row per submitted verification request.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.verification_requests (
    -- Primary key (generated by the app via crypto.randomUUID())
    id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Who submitted it
    user_id             UUID        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

    -- ── Personal / Academic Info ──────────────────────────
    student_name        TEXT        NOT NULL,           -- "LASTNAME, FIRSTNAME MIDDLENAME"
    degree_diploma      TEXT,                           -- e.g. "Bachelor of Science in IT"
    major_track         TEXT,                           -- e.g. "Web Development"
    student_status      TEXT        NOT NULL DEFAULT 'graduate'
                                    CHECK (student_status IN ('graduate', 'undergraduate')),
    date_of_graduation  TEXT,                           -- exact date OR "Approximate: YYYY"

    -- ── Enrollment Period ─────────────────────────────────
    term_started        TEXT,                           -- e.g. "1st Semester"
    school_year_started TEXT,                           -- e.g. "2019-2020"
    term_ended          TEXT,
    school_year_ended   TEXT,

    -- ── School Info ───────────────────────────────────────
    school_name         TEXT,
    school_address      TEXT,

    -- ── Uploaded Files (array of {name, url, type}) ───────
    uploaded_files      JSONB       NOT NULL DEFAULT '[]'::jsonb,

    -- ── Status & Review ───────────────────────────────────
    status              TEXT        NOT NULL DEFAULT 'pending'
                                    CHECK (status IN ('pending', 'verified', 'not_verified')),
    document_assessment TEXT,                           -- admin's assessment note
    admin_remarks       TEXT,                           -- admin's remarks/comments

    -- ── Timestamps ────────────────────────────────────────
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at         TIMESTAMPTZ                     -- set when admin changes status
);

-- Indexes: common query patterns in your JS
CREATE INDEX IF NOT EXISTS idx_vr_user_id    ON public.verification_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_vr_status     ON public.verification_requests(status);
CREATE INDEX IF NOT EXISTS idx_vr_created_at ON public.verification_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vr_name       ON public.verification_requests(student_name);

-- GIN index for fast JSONB file queries
CREATE INDEX IF NOT EXISTS idx_vr_files_gin  ON public.verification_requests USING GIN (uploaded_files);

-- Comments
COMMENT ON TABLE  public.verification_requests                   IS 'Student/client verification requests submitted through the portal.';
COMMENT ON COLUMN public.verification_requests.uploaded_files    IS 'Array of {name, url, type} objects stored in Supabase Storage.';
COMMENT ON COLUMN public.verification_requests.status            IS '"pending" = awaiting review, "verified" = approved, "not_verified" = rejected.';
COMMENT ON COLUMN public.verification_requests.document_assessment IS 'Admin assessment of submitted documents.';


-- ============================================================
-- SECTION 4: AUTO-UPDATE updated_at TRIGGER
-- Automatically sets updated_at = NOW() on any row update.
-- ============================================================

-- Reusable trigger function
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach to users
DROP TRIGGER IF EXISTS trg_users_updated_at ON public.users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Attach to verification_requests
DROP TRIGGER IF EXISTS trg_vr_updated_at ON public.verification_requests;
CREATE TRIGGER trg_vr_updated_at
    BEFORE UPDATE ON public.verification_requests
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- SECTION 5: AUTO-SET reviewed_at TRIGGER
-- Sets reviewed_at when status changes from "pending".
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_reviewed_at()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status = 'pending' AND NEW.status <> 'pending' THEN
        NEW.reviewed_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_vr_reviewed_at ON public.verification_requests;
CREATE TRIGGER trg_vr_reviewed_at
    BEFORE UPDATE ON public.verification_requests
    FOR EACH ROW EXECUTE FUNCTION public.set_reviewed_at();


-- ============================================================
-- SECTION 6: ROW LEVEL SECURITY (RLS)
-- Controls who can read/write which rows.
-- ============================================================

-- Enable RLS
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_requests ENABLE ROW LEVEL SECURITY;


-- ── users table policies ─────────────────────────────────────

DROP POLICY IF EXISTS "users: read own profile"  ON public.users;
DROP POLICY IF EXISTS "users: update own profile" ON public.users;
DROP POLICY IF EXISTS "users: admin read all"     ON public.users;
DROP POLICY IF EXISTS "users: insert own profile" ON public.users;

-- Users can read their own profile
CREATE POLICY "users: read own profile"
    ON public.users FOR SELECT
    USING (auth.uid() = id);

-- Users can update their own profile
CREATE POLICY "users: update own profile"
    ON public.users FOR UPDATE
    USING (auth.uid() = id);

-- Users can insert their own profile on signup
CREATE POLICY "users: insert own profile"
    ON public.users FOR INSERT
    WITH CHECK (auth.uid() = id);

-- Admins can read ALL user profiles
CREATE POLICY "users: admin read all"
    ON public.users FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );


-- ── verification_requests table policies ─────────────────────

DROP POLICY IF EXISTS "requests: user read own"   ON public.verification_requests;
DROP POLICY IF EXISTS "requests: user insert own" ON public.verification_requests;
DROP POLICY IF EXISTS "requests: admin read all"  ON public.verification_requests;
DROP POLICY IF EXISTS "requests: admin update"    ON public.verification_requests;
DROP POLICY IF EXISTS "requests: admin delete"    ON public.verification_requests;

-- Students can read ONLY their own requests
CREATE POLICY "requests: user read own"
    ON public.verification_requests FOR SELECT
    USING (auth.uid() = user_id);

-- Students can insert their own requests
CREATE POLICY "requests: user insert own"
    ON public.verification_requests FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Students CANNOT update or delete (read-only after submission)
-- (No UPDATE/DELETE policies for users = denied by default)

-- Admins can read ALL requests
CREATE POLICY "requests: admin read all"
    ON public.verification_requests FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );

-- Admins can update any request (status, remarks, assessment)
CREATE POLICY "requests: admin update"
    ON public.verification_requests FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );

-- Admins can delete requests (optional — remove if you want soft-delete only)
CREATE POLICY "requests: admin delete"
    ON public.verification_requests FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );


-- ============================================================
-- SECTION 7: AUTO-CREATE USER PROFILE ON SIGNUP
-- When a new user signs up via Supabase Auth, automatically
-- insert a row into public.users with role = 'user'.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, display_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
        'user'
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_on_auth_user_created ON auth.users;
CREATE TRIGGER trg_on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- SECTION 8: STORAGE BUCKET POLICIES
-- Run these AFTER creating the "verification-files" bucket
-- in Supabase → Storage → New Bucket (set to private).
-- ============================================================

-- Allow authenticated users to upload to their own folder
-- Path format: verificationFiles/{user_id}/{request_id}/{filename}
INSERT INTO storage.buckets (id, name, public)
VALUES ('verification-files', 'verification-files', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "storage: user upload own files"  ON storage.objects;
DROP POLICY IF EXISTS "storage: user read own files"   ON storage.objects;
DROP POLICY IF EXISTS "storage: admin read all files"  ON storage.objects;
DROP POLICY IF EXISTS "storage: admin delete files"    ON storage.objects;

-- Students can upload files under their own user_id folder
CREATE POLICY "storage: user upload own files"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'verification-files'
        AND auth.uid()::text = (string_to_array(name, '/'))[2]
    );

-- Students can read their own uploaded files
CREATE POLICY "storage: user read own files"
    ON storage.objects FOR SELECT
    USING (
        bucket_id = 'verification-files'
        AND auth.uid()::text = (string_to_array(name, '/'))[2]
    );

-- Admins can read ALL uploaded files
CREATE POLICY "storage: admin read all files"
    ON storage.objects FOR SELECT
    USING (
        bucket_id = 'verification-files'
        AND EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );

-- Admins can delete files (if needed)
CREATE POLICY "storage: admin delete files"
    ON storage.objects FOR DELETE
    USING (
        bucket_id = 'verification-files'
        AND EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );


-- ============================================================
-- SECTION 9: SEED — CREATE FIRST ADMIN ACCOUNT
-- After running this schema, manually create an admin user:
--
-- 1. Go to Supabase → Authentication → Users → Add User
--    Email: admin@csu.edu.ph   Password: (your choice)
-- 2. Copy the new user's UUID
-- 3. Run this query (replace the UUID):
--
--    UPDATE public.users
--    SET role = 'admin', display_name = 'Registrar Admin'
--    WHERE id = '<paste-uuid-here>';
--
-- ============================================================


-- ============================================================
-- SECTION 10: USEFUL VIEWS (optional, for reports/exports)
-- ============================================================

-- View: pending requests with submitter email
CREATE OR REPLACE VIEW public.v_pending_requests AS
SELECT
    vr.id,
    vr.student_name,
    vr.degree_diploma,
    vr.student_status,
    vr.school_name,
    vr.created_at,
    u.email AS submitter_email
FROM public.verification_requests vr
JOIN public.users u ON u.id = vr.user_id
WHERE vr.status = 'pending'
ORDER BY vr.created_at ASC;

-- View: full request summary for admin dashboard
CREATE OR REPLACE VIEW public.v_all_requests AS
SELECT
    vr.*,
    u.email          AS submitter_email,
    u.display_name   AS submitter_display_name
FROM public.verification_requests vr
JOIN public.users u ON u.id = vr.user_id
ORDER BY vr.created_at DESC;

COMMENT ON VIEW public.v_pending_requests IS 'All pending requests sorted oldest-first (for FIFO processing).';
COMMENT ON VIEW public.v_all_requests     IS 'All requests with submitter info joined — use for admin reports.';


-- ============================================================
-- SECTION 11: STUDENT RECORDS TABLE
-- Stores imported CSV data of graduates, undergraduates,
-- transferees, and dropouts for the Records section.
-- Run this in Supabase SQL Editor to add the student_records table.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.student_records (
    id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_name    TEXT        NOT NULL,
    student_id      TEXT,
    program         TEXT,
    status          TEXT        CHECK (status IN ('graduate', 'undergraduate', 'transferee', 'dropout')),
    year_level      TEXT,
    term            TEXT,
    school_year     TEXT,
    imported_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    imported_by     UUID        REFERENCES public.users(id) ON DELETE SET NULL
);

-- Indexes for common query patterns (search, filter by status, school year)
CREATE INDEX IF NOT EXISTS idx_sr_name        ON public.student_records(student_name);
CREATE INDEX IF NOT EXISTS idx_sr_status      ON public.student_records(status);
CREATE INDEX IF NOT EXISTS idx_sr_school_year ON public.student_records(school_year);
CREATE INDEX IF NOT EXISTS idx_sr_term        ON public.student_records(term);

COMMENT ON TABLE  public.student_records              IS 'Imported student database — graduates, undergraduates, transferees, dropouts.';
COMMENT ON COLUMN public.student_records.status       IS 'One of: graduate, undergraduate, transferee, dropout.';
COMMENT ON COLUMN public.student_records.imported_by  IS 'UUID of the admin who imported this record.';

-- Enable Row Level Security
ALTER TABLE public.student_records ENABLE ROW LEVEL SECURITY;

-- Admins can do everything on student_records
DROP POLICY IF EXISTS "records: admin all" ON public.student_records;
CREATE POLICY "records: admin all"
    ON public.student_records FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );

-- Users (students) can read student_records for self-lookup purposes
DROP POLICY IF EXISTS "records: user read" ON public.student_records;
CREATE POLICY "records: user read"
    ON public.student_records FOR SELECT
    USING (auth.uid() IS NOT NULL);


-- ============================================================
-- DONE — Schema is ready.
-- ============================================================
